point_of_contact: @snowflakedb/client
distributed: true
modified: true
legal_exception: false
production: true
code_owners_file_present: true
jira_project_issue_type: Bug
jira_area: Developer Platform
