codecov:
  notify:
    wait_for_ci: true
    require_ci_to_pass: true

flag_management:
  default_rules:
    carryforward: false
    carryforward_mode: "all"

flags:
  rust:
    paths: ["sf_core/"]
  jdbc:
    paths: ["jdbc/", "jdbc_bridge/"]
  python:
    paths: ["pep249_dbapi/"]
  odbc:
    paths: ["odbc/"]

x-component: &component
  target: auto
  threshold: 2%
  base: auto
  if_ci_failed: error

x-patch-component: &patch-component
  target: 75%
  threshold: 5%
  base: auto
  if_ci_failed: error

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      # Overall status waits for all expected coverage flags
      default:
        <<: *component
        flags: [rust, python, jdbc, odbc]
        flag_coverage_not_uploaded_behavior: exclude
      # Individual component statuses
      rust:    { <<: *component, flags: [rust] }
      python:  { <<: *component, flags: [python] }
      jdbc:    { <<: *component, flags: [jdbc] }
      odbc:    { <<: *component, flags: [odbc] }
        
    patch:
      # Overall patch status waits for all expected coverage flags
      default:
        <<: *patch-component
        flags: [rust, python, jdbc, odbc]
        flag_coverage_not_uploaded_behavior: exclude
      # Individual component statuses
      rust:    { <<: *patch-component, flags: [rust] }
      python:  { <<: *patch-component, flags: [python] }
      jdbc:    { <<: *patch-component, flags: [jdbc] }
      odbc:    { <<: *patch-component, flags: [odbc] }

comment:
  layout: "header,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  branches: ["main", "develop"]
  show_carryforward_flags: true

ignore:
  # Test files and documentation
  - "tests/"
  - "tests/**/*"
  - "**/tests/"
  - "**/tests/**/*"
  - "**/*.md"
  - "odbc_tests/"
  - "odbc_tests/**/*"
  - "scripts/"
  
  # Specific test paths to exclude
  - "sf_core/tests/**"
  - "**/tests/common/**"
  - "tests/common/**"
  - "tests/tests_format_validator/**"
  
  # Build artifacts
  - "**/target/"
  - "**/build/"
  
  # Configuration files
  - "**/*.toml"
  - "**/*.lock"
  
  # Python artifacts
  - "**/__pycache__/"
  - "**/*.pyc"
  - "**/*.pyo"
  - "**/.pytest_cache/"
  - "**/.tox/"
  - "**/dist/"
  - "**/*.egg-info/"
  
  # Generated code
  - "**/thrift_gen/"
  - "**/gen-*/"
  
  # Java/Gradle artifacts
  - "**/.gradle/"
  - "**/gradlew*"
  - "**/*.class"
  
  # CMake artifacts
  - "**/CMakeCache.txt"
  - "**/CMakeFiles/"
  - "**/cmake_install.cmake"
  - "**/cmake-build/"
  
  # IDE and OS files
  - "**/.idea/"
  - "**/.vscode/"
  - "**/.DS_Store"
  - "**/*.swp"

github_checks:
  annotations: true
