codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
    require_ci_to_pass: true

flags:
  rust-core:
    paths: ["sf_core/**"]
    carryforward: false
  python:
    paths: ["pep249_dbapi/**"]
    carryforward: false
  jdbc:
    paths: ["jdbc/**", "jdbc_bridge/**"]
    carryforward: false
  odbc:
    paths: ["odbc/**"]
    carryforward: false



coverage:
  precision: 2
  round: down
  range: "60...90"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        flags: [rust-core, python, jdbc, odbc]
        flag_coverage_not_uploaded_behavior: exclude
    patch: off

comment:
  layout: "header,diff,components,tree"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  branches: ["main", "develop"]
  show_carryforward_flags: false

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 2%

  individual_components:
    - component_id: rust-core
      name: "Rust Core"
      paths:
        - "sf_core/**"
    - component_id: python
      name: "Python Driver"
      paths:
        - "pep249_dbapi/**"
    - component_id: jdbc
      name: "JDBC Driver"
      paths:
        - "jdbc/**"
        - "jdbc_bridge/**"
    - component_id: odbc
      name: "ODBC Driver"
      paths:
        - "odbc/**"

ignore:
  # Test files and documentation
  - "tests/"
  - "tests/**/*"
  - "**/tests/"
  - "**/tests/**/*"
  - "**/*.md"
  - "odbc_tests/"
  - "odbc_tests/**/*"
  - "scripts/"
  
  # Specific test paths to exclude
  - "sf_core/tests/**"
  - "**/tests/common/**"
  - "tests/common/**"
  - "tests/tests_format_validator/**"
  
  # Build artifacts
  - "**/target/"
  - "**/build/"
  
  # Configuration files
  - "**/*.toml"
  - "**/*.lock"
  
  # Python artifacts
  - "**/__pycache__/"
  - "**/*.pyc"
  - "**/*.pyo"
  - "**/.pytest_cache/"
  - "**/.tox/"
  - "**/dist/"
  - "**/*.egg-info/"
  
  # Generated code
  - "**/protobuf_gen/"
  - "**/gen-*/"
  
  # Java/Gradle artifacts
  - "**/.gradle/"
  - "**/gradlew*"
  - "**/*.class"
  
  # CMake artifacts
  - "**/CMakeCache.txt"
  - "**/CMakeFiles/"
  - "**/cmake_install.cmake"
  - "**/cmake-build/"
  
  # IDE and OS files
  - "**/.idea/"
  - "**/.vscode/"
  - "**/.DS_Store"
  - "**/*.swp"

github_checks:
  annotations: true